language: php

cache:
  directories:
    - $HOME/.chapi/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  - composer self-update
  - composer install --prefer-source
#  - cd test/

script: ./bin/phpunit --coverage-clover=coverage.clover -c test/phpunit.xml test/

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
