#parameters:
#    # ...
#    mailer.transport: sendmail
#
#services:
#    mailer:
#        class:     Mailer
#        arguments: ["%mailer.transport%"]
#    newsletter_manager:
#        class:     NewsletterManager
#        calls:
#            - [setMailer, ["@mailer"]]

imports:
    - { resource: "businesscase/job_comparison.yml" }
    - { resource: "businesscase/job_management.yml" }
    - { resource: "component/cache.yml" }
    - { resource: "component/chronos_api_client.yml" }
    - { resource: "component/comparison.yml" }
    - { resource: "component/date_period_factory.yml" }
    - { resource: "component/http_client.yml" }
    - { resource: "service/job_index.yml" }
    - { resource: "service/job_repository.yml" }

