services:
  JobRepositoryChronos:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeChronos"
      - "@FilterChronosEntity"

  JobRepositoryFileSystemChronos:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeFileSystemChronos"
      - "@FilterChronosEntity"

  JobRepositoryFileSystemMarathon:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeFileSystemMarathon"
      - "@FilterMarathonEntity"

  JobRepositoryMarathon:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeMarathon"
      - "@FilterMarathonEntity"

  JobRepositoryBridgeChronos:
    class: Chapi\Service\JobRepository\BridgeChronos
    factory: "BridgeFactory:getChronosBridge"
    arguments:
      - "@ChronosApiClientInterface"
      - "@CacheInterface"
      - "@JobValidatorServiceInterface"
      - "@LoggerInterface"

  JobRepositoryBridgeFileSystemChronos:
    class: Chapi\Service\JobRepository\BridgeFileSystem
    factory: "BridgeFactory:getFilesystemBridge"
    arguments:
      - "@ExternalFileSystemService"
      - "@CacheInterface"
      - "%repository_dir%"
      - "@LoggerInterface"

  JobRepositoryBridgeFileSystemMarathon:
    class: Chapi\Service\JobRepository\BridgeFileSystem
    factory: "BridgeFactory:getFilesystemBridge"
    arguments:
      - "@ExternalFileSystemService"
      - "@CacheInterface"
      - "%repository_dir_marathon%"
      - "@LoggerInterface"

  JobRepositoryBridgeMarathon:
    class: Chapi\Service\JobRepository\BridgeMarathon
    factory: "BridgeFactory:getMarathonBridge"
    arguments:
      - "@MarathonApiClientInterface"
      - "@CacheInterface"
      - "@JobValidatorServiceInterface"
      - "@LoggerInterface"

  ExternalFileSystemService:
    class: \Symfony\Component\Filesystem\Filesystem

  FilterChronosEntity:
    class: Chapi\Service\JobRepository\FilterChronosEntity

  FilterMarathonEntity:
    class: Chapi\Service\JobRepository\FilterMarathonEntity


  BridgeFactory:
    class: Chapi\Service\JobRepository\BridgeFactory
